name: Playwright Tests
on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: which node
      - run: which npm
      # - uses: actions/checkout@v4
      # # cached node
      # - name: Fetch cached node installation
      #   id: cached-node
      #   uses: actions/cache@v3
      #   with:
      #     path: |
      #       ~/.npm
      #       /usr/bin/node
      #     key: "node-installation"

      # # cached node_modules
      # - name: Fetch cached node_modules
      #   id: cached-node-modules
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/node_modules
      #     key: "node-installation"
      # - uses: actions/setup-node@v4
      #   with:
      #     node-version: lts/*
      # - name: Install dependencies
      #   run: npm ci
      # - name: Install Playwright Browsers
      #   run: npx playwright install --with-deps
      # - name: Run Playwright tests
      #   run: npx playwright test
      # - uses: actions/upload-artifact@v4
      #   if: ${{ !cancelled() }}
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 1
